/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Painter1RouteImport } from './routes/painter1'
import { Route as Painter2RouteImport } from './routes/painter2'
import { Route as Painter3RouteImport } from './routes/painter3'
import { Route as Painter4RouteImport } from './routes/painter4'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AdminContractorResearchRouteImport } from './routes/admin_.contractor-research'
import { Route as AdminObservabilityRouteImport } from './routes/admin_.observability'
import { Route as AdminTracesRouteImport } from './routes/admin_.traces'
import { Route as BookingConfirmationRouteImport } from './routes/booking.confirmation'
import { Route as BookingReturnRouteImport } from './routes/booking.return'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as LpWebsiteIdRouteImport } from './routes/lp/$websiteId'
import { Route as SetupWebsiteIdRouteImport } from './routes/setup.$websiteId'
import { Route as TemplatePlumberRouteImport } from './routes/template.plumber'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as TemplatesLandscapeRouteImport } from './routes/templates.landscape'
import { Route as TemplatesPainterRouteImport } from './routes/templates.painter'
import { Route as TemplatesPainter1RouteImport } from './routes/templates.painter1'
import { Route as TemplatesPainter10RouteImport } from './routes/templates.painter10'
import { Route as TemplatesPainter11RouteImport } from './routes/templates.painter11'
import { Route as TemplatesPainter12RouteImport } from './routes/templates.painter12'
import { Route as TemplatesPainter13RouteImport } from './routes/templates.painter13'
import { Route as TemplatesPainter14RouteImport } from './routes/templates.painter14'
import { Route as TemplatesPainter15RouteImport } from './routes/templates.painter15'
import { Route as TemplatesPainter16RouteImport } from './routes/templates.painter16'
import { Route as TemplatesPainter17RouteImport } from './routes/templates.painter17'
import { Route as TemplatesPainter18RouteImport } from './routes/templates.painter18'
import { Route as TemplatesPainter4RouteImport } from './routes/templates.painter4'
import { Route as TemplatesPainter5RouteImport } from './routes/templates.painter5'
import { Route as TemplatesPainter6RouteImport } from './routes/templates.painter6'
import { Route as TemplatesPainter7RouteImport } from './routes/templates.painter7'
import { Route as TemplatesPainter8RouteImport } from './routes/templates.painter8'
import { Route as TemplatesPlumberRouteImport } from './routes/templates.plumber'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as ApiAdminCalendarRepairRouteImport } from './routes/api/admin/calendar-repair'
import { Route as ApiAgentMessageRouteImport } from './routes/api/agent/message'
import { Route as ApiCronBookingRouteImport } from './routes/api/cron/booking'
import { Route as ApiCronGenerationMonitorRouteImport } from './routes/api/cron/generation-monitor'
import { Route as ApiCronLeadRetentionRouteImport } from './routes/api/cron/lead-retention'
import { Route as ApiCronPipedreamInboxRouteImport } from './routes/api/cron/pipedream-inbox'
import { Route as ApiCronStripeInboxRouteImport } from './routes/api/cron/stripe-inbox'
import { Route as ApiPipedreamWebhookRouteImport } from './routes/api/pipedream/webhook'
import { Route as ApiPublicAgentLogsRouteImport } from './routes/api/public/agent-logs'
import { Route as ApiResendWebhookRouteImport } from './routes/api/resend/webhook'
import { Route as ApiStripeConnectWebhookRouteImport } from './routes/api/stripe/connect-webhook'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as SetupWebsiteIdIndexRouteImport } from './routes/setup.$websiteId.index'
import { Route as SetupWebsiteIdAvailabilityRouteImport } from './routes/setup.$websiteId.availability'
import { Route as SetupWebsiteIdCalendarRouteImport } from './routes/setup.$websiteId.calendar'
import { Route as SetupWebsiteIdPaymentsRouteImport } from './routes/setup.$websiteId.payments'
import { Route as UserUserIdEditModeRouteImport } from './routes/user/$userId.edit-mode'
import { Route as ApiBookingAttachmentsProofRouteImport } from './routes/api/booking/attachments/proof'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiBookingAttachmentsAttachmentIdDownloadRouteImport } from './routes/api/booking/attachments/$attachmentId/download'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Painter1Route = Painter1RouteImport.update({
  id: '/painter1',
  path: '/painter1',
  getParentRoute: () => rootRouteImport,
} as any)
const Painter2Route = Painter2RouteImport.update({
  id: '/painter2',
  path: '/painter2',
  getParentRoute: () => rootRouteImport,
} as any)
const Painter3Route = Painter3RouteImport.update({
  id: '/painter3',
  path: '/painter3',
  getParentRoute: () => rootRouteImport,
} as any)
const Painter4Route = Painter4RouteImport.update({
  id: '/painter4',
  path: '/painter4',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContractorResearchRoute = AdminContractorResearchRouteImport.update({
  id: '/admin_/contractor-research',
  path: '/admin/contractor-research',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminObservabilityRoute = AdminObservabilityRouteImport.update({
  id: '/admin_/observability',
  path: '/admin/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTracesRoute = AdminTracesRouteImport.update({
  id: '/admin_/traces',
  path: '/admin/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmationRoute = BookingConfirmationRouteImport.update({
  id: '/booking/confirmation',
  path: '/booking/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingReturnRoute = BookingReturnRouteImport.update({
  id: '/booking/return',
  path: '/booking/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LpWebsiteIdRoute = LpWebsiteIdRouteImport.update({
  id: '/lp/$websiteId',
  path: '/lp/$websiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupWebsiteIdRoute = SetupWebsiteIdRouteImport.update({
  id: '/setup/$websiteId',
  path: '/setup/$websiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatePlumberRoute = TemplatePlumberRouteImport.update({
  id: '/template/plumber',
  path: '/template/plumber',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesLandscapeRoute = TemplatesLandscapeRouteImport.update({
  id: '/templates/landscape',
  path: '/templates/landscape',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainterRoute = TemplatesPainterRouteImport.update({
  id: '/templates/painter',
  path: '/templates/painter',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter1Route = TemplatesPainter1RouteImport.update({
  id: '/templates/painter1',
  path: '/templates/painter1',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter10Route = TemplatesPainter10RouteImport.update({
  id: '/templates/painter10',
  path: '/templates/painter10',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter11Route = TemplatesPainter11RouteImport.update({
  id: '/templates/painter11',
  path: '/templates/painter11',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter12Route = TemplatesPainter12RouteImport.update({
  id: '/templates/painter12',
  path: '/templates/painter12',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter13Route = TemplatesPainter13RouteImport.update({
  id: '/templates/painter13',
  path: '/templates/painter13',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter14Route = TemplatesPainter14RouteImport.update({
  id: '/templates/painter14',
  path: '/templates/painter14',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter15Route = TemplatesPainter15RouteImport.update({
  id: '/templates/painter15',
  path: '/templates/painter15',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter16Route = TemplatesPainter16RouteImport.update({
  id: '/templates/painter16',
  path: '/templates/painter16',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter17Route = TemplatesPainter17RouteImport.update({
  id: '/templates/painter17',
  path: '/templates/painter17',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter18Route = TemplatesPainter18RouteImport.update({
  id: '/templates/painter18',
  path: '/templates/painter18',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter4Route = TemplatesPainter4RouteImport.update({
  id: '/templates/painter4',
  path: '/templates/painter4',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter5Route = TemplatesPainter5RouteImport.update({
  id: '/templates/painter5',
  path: '/templates/painter5',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter6Route = TemplatesPainter6RouteImport.update({
  id: '/templates/painter6',
  path: '/templates/painter6',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter7Route = TemplatesPainter7RouteImport.update({
  id: '/templates/painter7',
  path: '/templates/painter7',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPainter8Route = TemplatesPainter8RouteImport.update({
  id: '/templates/painter8',
  path: '/templates/painter8',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesPlumberRoute = TemplatesPlumberRouteImport.update({
  id: '/templates/plumber',
  path: '/templates/plumber',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCalendarRepairRoute = ApiAdminCalendarRepairRouteImport.update({
  id: '/api/admin/calendar-repair',
  path: '/api/admin/calendar-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMessageRoute = ApiAgentMessageRouteImport.update({
  id: '/api/agent/message',
  path: '/api/agent/message',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBookingRoute = ApiCronBookingRouteImport.update({
  id: '/api/cron/booking',
  path: '/api/cron/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGenerationMonitorRoute =
  ApiCronGenerationMonitorRouteImport.update({
    id: '/api/cron/generation-monitor',
    path: '/api/cron/generation-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronLeadRetentionRoute = ApiCronLeadRetentionRouteImport.update({
  id: '/api/cron/lead-retention',
  path: '/api/cron/lead-retention',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPipedreamInboxRoute = ApiCronPipedreamInboxRouteImport.update({
  id: '/api/cron/pipedream-inbox',
  path: '/api/cron/pipedream-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronStripeInboxRoute = ApiCronStripeInboxRouteImport.update({
  id: '/api/cron/stripe-inbox',
  path: '/api/cron/stripe-inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPipedreamWebhookRoute = ApiPipedreamWebhookRouteImport.update({
  id: '/api/pipedream/webhook',
  path: '/api/pipedream/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentLogsRoute = ApiPublicAgentLogsRouteImport.update({
  id: '/api/public/agent-logs',
  path: '/api/public/agent-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResendWebhookRoute = ApiResendWebhookRouteImport.update({
  id: '/api/resend/webhook',
  path: '/api/resend/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConnectWebhookRoute = ApiStripeConnectWebhookRouteImport.update({
  id: '/api/stripe/connect-webhook',
  path: '/api/stripe/connect-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupWebsiteIdIndexRoute = SetupWebsiteIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupWebsiteIdRoute,
} as any)
const SetupWebsiteIdAvailabilityRoute =
  SetupWebsiteIdAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => SetupWebsiteIdRoute,
  } as any)
const SetupWebsiteIdCalendarRoute = SetupWebsiteIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SetupWebsiteIdRoute,
} as any)
const SetupWebsiteIdPaymentsRoute = SetupWebsiteIdPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SetupWebsiteIdRoute,
} as any)
const UserUserIdEditModeRoute = UserUserIdEditModeRouteImport.update({
  id: '/edit-mode',
  path: '/edit-mode',
  getParentRoute: () => UserUserIdRoute,
} as any)
const ApiBookingAttachmentsProofRoute =
  ApiBookingAttachmentsProofRouteImport.update({
    id: '/api/booking/attachments/proof',
    path: '/api/booking/attachments/proof',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookingAttachmentsAttachmentIdDownloadRoute =
  ApiBookingAttachmentsAttachmentIdDownloadRouteImport.update({
    id: '/api/booking/attachments/$attachmentId/download',
    path: '/api/booking/attachments/$attachmentId/download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/painter1': typeof Painter1Route
  '/painter2': typeof Painter2Route
  '/painter3': typeof Painter3Route
  '/painter4': typeof Painter4Route
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/contractor-research': typeof AdminContractorResearchRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/traces': typeof AdminTracesRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/return': typeof BookingReturnRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/lp/$websiteId': typeof LpWebsiteIdRoute
  '/setup/$websiteId': typeof SetupWebsiteIdRouteWithChildren
  '/template/plumber': typeof TemplatePlumberRoute
  '/templates/landscape': typeof TemplatesLandscapeRoute
  '/templates/painter': typeof TemplatesPainterRoute
  '/templates/painter1': typeof TemplatesPainter1Route
  '/templates/painter10': typeof TemplatesPainter10Route
  '/templates/painter11': typeof TemplatesPainter11Route
  '/templates/painter12': typeof TemplatesPainter12Route
  '/templates/painter13': typeof TemplatesPainter13Route
  '/templates/painter14': typeof TemplatesPainter14Route
  '/templates/painter15': typeof TemplatesPainter15Route
  '/templates/painter16': typeof TemplatesPainter16Route
  '/templates/painter17': typeof TemplatesPainter17Route
  '/templates/painter18': typeof TemplatesPainter18Route
  '/templates/painter4': typeof TemplatesPainter4Route
  '/templates/painter5': typeof TemplatesPainter5Route
  '/templates/painter6': typeof TemplatesPainter6Route
  '/templates/painter7': typeof TemplatesPainter7Route
  '/templates/painter8': typeof TemplatesPainter8Route
  '/templates/plumber': typeof TemplatesPlumberRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/templates/': typeof TemplatesIndexRoute
  '/api/admin/calendar-repair': typeof ApiAdminCalendarRepairRoute
  '/api/agent/message': typeof ApiAgentMessageRoute
  '/api/cron/booking': typeof ApiCronBookingRoute
  '/api/cron/generation-monitor': typeof ApiCronGenerationMonitorRoute
  '/api/cron/lead-retention': typeof ApiCronLeadRetentionRoute
  '/api/cron/pipedream-inbox': typeof ApiCronPipedreamInboxRoute
  '/api/cron/stripe-inbox': typeof ApiCronStripeInboxRoute
  '/api/pipedream/webhook': typeof ApiPipedreamWebhookRoute
  '/api/public/agent-logs': typeof ApiPublicAgentLogsRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/api/stripe/connect-webhook': typeof ApiStripeConnectWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/setup/$websiteId/availability': typeof SetupWebsiteIdAvailabilityRoute
  '/setup/$websiteId/calendar': typeof SetupWebsiteIdCalendarRoute
  '/setup/$websiteId/payments': typeof SetupWebsiteIdPaymentsRoute
  '/user/$userId/edit-mode': typeof UserUserIdEditModeRoute
  '/setup/$websiteId/': typeof SetupWebsiteIdIndexRoute
  '/api/booking/attachments/proof': typeof ApiBookingAttachmentsProofRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/booking/attachments/$attachmentId/download': typeof ApiBookingAttachmentsAttachmentIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/painter1': typeof Painter1Route
  '/painter2': typeof Painter2Route
  '/painter3': typeof Painter3Route
  '/painter4': typeof Painter4Route
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/contractor-research': typeof AdminContractorResearchRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/traces': typeof AdminTracesRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/return': typeof BookingReturnRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/lp/$websiteId': typeof LpWebsiteIdRoute
  '/template/plumber': typeof TemplatePlumberRoute
  '/templates/landscape': typeof TemplatesLandscapeRoute
  '/templates/painter': typeof TemplatesPainterRoute
  '/templates/painter1': typeof TemplatesPainter1Route
  '/templates/painter10': typeof TemplatesPainter10Route
  '/templates/painter11': typeof TemplatesPainter11Route
  '/templates/painter12': typeof TemplatesPainter12Route
  '/templates/painter13': typeof TemplatesPainter13Route
  '/templates/painter14': typeof TemplatesPainter14Route
  '/templates/painter15': typeof TemplatesPainter15Route
  '/templates/painter16': typeof TemplatesPainter16Route
  '/templates/painter17': typeof TemplatesPainter17Route
  '/templates/painter18': typeof TemplatesPainter18Route
  '/templates/painter4': typeof TemplatesPainter4Route
  '/templates/painter5': typeof TemplatesPainter5Route
  '/templates/painter6': typeof TemplatesPainter6Route
  '/templates/painter7': typeof TemplatesPainter7Route
  '/templates/painter8': typeof TemplatesPainter8Route
  '/templates/plumber': typeof TemplatesPlumberRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/templates': typeof TemplatesIndexRoute
  '/api/admin/calendar-repair': typeof ApiAdminCalendarRepairRoute
  '/api/agent/message': typeof ApiAgentMessageRoute
  '/api/cron/booking': typeof ApiCronBookingRoute
  '/api/cron/generation-monitor': typeof ApiCronGenerationMonitorRoute
  '/api/cron/lead-retention': typeof ApiCronLeadRetentionRoute
  '/api/cron/pipedream-inbox': typeof ApiCronPipedreamInboxRoute
  '/api/cron/stripe-inbox': typeof ApiCronStripeInboxRoute
  '/api/pipedream/webhook': typeof ApiPipedreamWebhookRoute
  '/api/public/agent-logs': typeof ApiPublicAgentLogsRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/api/stripe/connect-webhook': typeof ApiStripeConnectWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/setup/$websiteId/availability': typeof SetupWebsiteIdAvailabilityRoute
  '/setup/$websiteId/calendar': typeof SetupWebsiteIdCalendarRoute
  '/setup/$websiteId/payments': typeof SetupWebsiteIdPaymentsRoute
  '/user/$userId/edit-mode': typeof UserUserIdEditModeRoute
  '/setup/$websiteId': typeof SetupWebsiteIdIndexRoute
  '/api/booking/attachments/proof': typeof ApiBookingAttachmentsProofRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/booking/attachments/$attachmentId/download': typeof ApiBookingAttachmentsAttachmentIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bookings': typeof BookingsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/painter1': typeof Painter1Route
  '/painter2': typeof Painter2Route
  '/painter3': typeof Painter3Route
  '/painter4': typeof Painter4Route
  '/verify-otp': typeof VerifyOtpRoute
  '/admin_/contractor-research': typeof AdminContractorResearchRoute
  '/admin_/observability': typeof AdminObservabilityRoute
  '/admin_/traces': typeof AdminTracesRoute
  '/booking/confirmation': typeof BookingConfirmationRoute
  '/booking/return': typeof BookingReturnRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/lp/$websiteId': typeof LpWebsiteIdRoute
  '/setup/$websiteId': typeof SetupWebsiteIdRouteWithChildren
  '/template/plumber': typeof TemplatePlumberRoute
  '/templates/landscape': typeof TemplatesLandscapeRoute
  '/templates/painter': typeof TemplatesPainterRoute
  '/templates/painter1': typeof TemplatesPainter1Route
  '/templates/painter10': typeof TemplatesPainter10Route
  '/templates/painter11': typeof TemplatesPainter11Route
  '/templates/painter12': typeof TemplatesPainter12Route
  '/templates/painter13': typeof TemplatesPainter13Route
  '/templates/painter14': typeof TemplatesPainter14Route
  '/templates/painter15': typeof TemplatesPainter15Route
  '/templates/painter16': typeof TemplatesPainter16Route
  '/templates/painter17': typeof TemplatesPainter17Route
  '/templates/painter18': typeof TemplatesPainter18Route
  '/templates/painter4': typeof TemplatesPainter4Route
  '/templates/painter5': typeof TemplatesPainter5Route
  '/templates/painter6': typeof TemplatesPainter6Route
  '/templates/painter7': typeof TemplatesPainter7Route
  '/templates/painter8': typeof TemplatesPainter8Route
  '/templates/plumber': typeof TemplatesPlumberRoute
  '/user/$userId': typeof UserUserIdRouteWithChildren
  '/templates/': typeof TemplatesIndexRoute
  '/api/admin/calendar-repair': typeof ApiAdminCalendarRepairRoute
  '/api/agent/message': typeof ApiAgentMessageRoute
  '/api/cron/booking': typeof ApiCronBookingRoute
  '/api/cron/generation-monitor': typeof ApiCronGenerationMonitorRoute
  '/api/cron/lead-retention': typeof ApiCronLeadRetentionRoute
  '/api/cron/pipedream-inbox': typeof ApiCronPipedreamInboxRoute
  '/api/cron/stripe-inbox': typeof ApiCronStripeInboxRoute
  '/api/pipedream/webhook': typeof ApiPipedreamWebhookRoute
  '/api/public/agent-logs': typeof ApiPublicAgentLogsRoute
  '/api/resend/webhook': typeof ApiResendWebhookRoute
  '/api/stripe/connect-webhook': typeof ApiStripeConnectWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/setup/$websiteId/availability': typeof SetupWebsiteIdAvailabilityRoute
  '/setup/$websiteId/calendar': typeof SetupWebsiteIdCalendarRoute
  '/setup/$websiteId/payments': typeof SetupWebsiteIdPaymentsRoute
  '/user/$userId/edit-mode': typeof UserUserIdEditModeRoute
  '/setup/$websiteId/': typeof SetupWebsiteIdIndexRoute
  '/api/booking/attachments/proof': typeof ApiBookingAttachmentsProofRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/api/booking/attachments/$attachmentId/download': typeof ApiBookingAttachmentsAttachmentIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bookings'
    | '/leads'
    | '/login'
    | '/painter1'
    | '/painter2'
    | '/painter3'
    | '/painter4'
    | '/verify-otp'
    | '/admin/contractor-research'
    | '/admin/observability'
    | '/admin/traces'
    | '/booking/confirmation'
    | '/booking/return'
    | '/checkout/success'
    | '/lp/$websiteId'
    | '/setup/$websiteId'
    | '/template/plumber'
    | '/templates/landscape'
    | '/templates/painter'
    | '/templates/painter1'
    | '/templates/painter10'
    | '/templates/painter11'
    | '/templates/painter12'
    | '/templates/painter13'
    | '/templates/painter14'
    | '/templates/painter15'
    | '/templates/painter16'
    | '/templates/painter17'
    | '/templates/painter18'
    | '/templates/painter4'
    | '/templates/painter5'
    | '/templates/painter6'
    | '/templates/painter7'
    | '/templates/painter8'
    | '/templates/plumber'
    | '/user/$userId'
    | '/templates/'
    | '/api/admin/calendar-repair'
    | '/api/agent/message'
    | '/api/cron/booking'
    | '/api/cron/generation-monitor'
    | '/api/cron/lead-retention'
    | '/api/cron/pipedream-inbox'
    | '/api/cron/stripe-inbox'
    | '/api/pipedream/webhook'
    | '/api/public/agent-logs'
    | '/api/resend/webhook'
    | '/api/stripe/connect-webhook'
    | '/api/stripe/webhook'
    | '/setup/$websiteId/availability'
    | '/setup/$websiteId/calendar'
    | '/setup/$websiteId/payments'
    | '/user/$userId/edit-mode'
    | '/setup/$websiteId/'
    | '/api/booking/attachments/proof'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/booking/attachments/$attachmentId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bookings'
    | '/leads'
    | '/login'
    | '/painter1'
    | '/painter2'
    | '/painter3'
    | '/painter4'
    | '/verify-otp'
    | '/admin/contractor-research'
    | '/admin/observability'
    | '/admin/traces'
    | '/booking/confirmation'
    | '/booking/return'
    | '/checkout/success'
    | '/lp/$websiteId'
    | '/template/plumber'
    | '/templates/landscape'
    | '/templates/painter'
    | '/templates/painter1'
    | '/templates/painter10'
    | '/templates/painter11'
    | '/templates/painter12'
    | '/templates/painter13'
    | '/templates/painter14'
    | '/templates/painter15'
    | '/templates/painter16'
    | '/templates/painter17'
    | '/templates/painter18'
    | '/templates/painter4'
    | '/templates/painter5'
    | '/templates/painter6'
    | '/templates/painter7'
    | '/templates/painter8'
    | '/templates/plumber'
    | '/user/$userId'
    | '/templates'
    | '/api/admin/calendar-repair'
    | '/api/agent/message'
    | '/api/cron/booking'
    | '/api/cron/generation-monitor'
    | '/api/cron/lead-retention'
    | '/api/cron/pipedream-inbox'
    | '/api/cron/stripe-inbox'
    | '/api/pipedream/webhook'
    | '/api/public/agent-logs'
    | '/api/resend/webhook'
    | '/api/stripe/connect-webhook'
    | '/api/stripe/webhook'
    | '/setup/$websiteId/availability'
    | '/setup/$websiteId/calendar'
    | '/setup/$websiteId/payments'
    | '/user/$userId/edit-mode'
    | '/setup/$websiteId'
    | '/api/booking/attachments/proof'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/booking/attachments/$attachmentId/download'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bookings'
    | '/leads'
    | '/login'
    | '/painter1'
    | '/painter2'
    | '/painter3'
    | '/painter4'
    | '/verify-otp'
    | '/admin_/contractor-research'
    | '/admin_/observability'
    | '/admin_/traces'
    | '/booking/confirmation'
    | '/booking/return'
    | '/checkout/success'
    | '/lp/$websiteId'
    | '/setup/$websiteId'
    | '/template/plumber'
    | '/templates/landscape'
    | '/templates/painter'
    | '/templates/painter1'
    | '/templates/painter10'
    | '/templates/painter11'
    | '/templates/painter12'
    | '/templates/painter13'
    | '/templates/painter14'
    | '/templates/painter15'
    | '/templates/painter16'
    | '/templates/painter17'
    | '/templates/painter18'
    | '/templates/painter4'
    | '/templates/painter5'
    | '/templates/painter6'
    | '/templates/painter7'
    | '/templates/painter8'
    | '/templates/plumber'
    | '/user/$userId'
    | '/templates/'
    | '/api/admin/calendar-repair'
    | '/api/agent/message'
    | '/api/cron/booking'
    | '/api/cron/generation-monitor'
    | '/api/cron/lead-retention'
    | '/api/cron/pipedream-inbox'
    | '/api/cron/stripe-inbox'
    | '/api/pipedream/webhook'
    | '/api/public/agent-logs'
    | '/api/resend/webhook'
    | '/api/stripe/connect-webhook'
    | '/api/stripe/webhook'
    | '/setup/$websiteId/availability'
    | '/setup/$websiteId/calendar'
    | '/setup/$websiteId/payments'
    | '/user/$userId/edit-mode'
    | '/setup/$websiteId/'
    | '/api/booking/attachments/proof'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/api/booking/attachments/$attachmentId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingsRoute: typeof BookingsRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  Painter1Route: typeof Painter1Route
  Painter2Route: typeof Painter2Route
  Painter3Route: typeof Painter3Route
  Painter4Route: typeof Painter4Route
  VerifyOtpRoute: typeof VerifyOtpRoute
  AdminContractorResearchRoute: typeof AdminContractorResearchRoute
  AdminObservabilityRoute: typeof AdminObservabilityRoute
  AdminTracesRoute: typeof AdminTracesRoute
  BookingConfirmationRoute: typeof BookingConfirmationRoute
  BookingReturnRoute: typeof BookingReturnRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  LpWebsiteIdRoute: typeof LpWebsiteIdRoute
  SetupWebsiteIdRoute: typeof SetupWebsiteIdRouteWithChildren
  TemplatePlumberRoute: typeof TemplatePlumberRoute
  TemplatesLandscapeRoute: typeof TemplatesLandscapeRoute
  TemplatesPainterRoute: typeof TemplatesPainterRoute
  TemplatesPainter1Route: typeof TemplatesPainter1Route
  TemplatesPainter10Route: typeof TemplatesPainter10Route
  TemplatesPainter11Route: typeof TemplatesPainter11Route
  TemplatesPainter12Route: typeof TemplatesPainter12Route
  TemplatesPainter13Route: typeof TemplatesPainter13Route
  TemplatesPainter14Route: typeof TemplatesPainter14Route
  TemplatesPainter15Route: typeof TemplatesPainter15Route
  TemplatesPainter16Route: typeof TemplatesPainter16Route
  TemplatesPainter17Route: typeof TemplatesPainter17Route
  TemplatesPainter18Route: typeof TemplatesPainter18Route
  TemplatesPainter4Route: typeof TemplatesPainter4Route
  TemplatesPainter5Route: typeof TemplatesPainter5Route
  TemplatesPainter6Route: typeof TemplatesPainter6Route
  TemplatesPainter7Route: typeof TemplatesPainter7Route
  TemplatesPainter8Route: typeof TemplatesPainter8Route
  TemplatesPlumberRoute: typeof TemplatesPlumberRoute
  UserUserIdRoute: typeof UserUserIdRouteWithChildren
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  ApiAdminCalendarRepairRoute: typeof ApiAdminCalendarRepairRoute
  ApiAgentMessageRoute: typeof ApiAgentMessageRoute
  ApiCronBookingRoute: typeof ApiCronBookingRoute
  ApiCronGenerationMonitorRoute: typeof ApiCronGenerationMonitorRoute
  ApiCronLeadRetentionRoute: typeof ApiCronLeadRetentionRoute
  ApiCronPipedreamInboxRoute: typeof ApiCronPipedreamInboxRoute
  ApiCronStripeInboxRoute: typeof ApiCronStripeInboxRoute
  ApiPipedreamWebhookRoute: typeof ApiPipedreamWebhookRoute
  ApiPublicAgentLogsRoute: typeof ApiPublicAgentLogsRoute
  ApiResendWebhookRoute: typeof ApiResendWebhookRoute
  ApiStripeConnectWebhookRoute: typeof ApiStripeConnectWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiBookingAttachmentsProofRoute: typeof ApiBookingAttachmentsProofRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  ApiBookingAttachmentsAttachmentIdDownloadRoute: typeof ApiBookingAttachmentsAttachmentIdDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painter1': {
      id: '/painter1'
      path: '/painter1'
      fullPath: '/painter1'
      preLoaderRoute: typeof Painter1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painter2': {
      id: '/painter2'
      path: '/painter2'
      fullPath: '/painter2'
      preLoaderRoute: typeof Painter2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painter3': {
      id: '/painter3'
      path: '/painter3'
      fullPath: '/painter3'
      preLoaderRoute: typeof Painter3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painter4': {
      id: '/painter4'
      path: '/painter4'
      fullPath: '/painter4'
      preLoaderRoute: typeof Painter4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/contractor-research': {
      id: '/admin_/contractor-research'
      path: '/admin/contractor-research'
      fullPath: '/admin/contractor-research'
      preLoaderRoute: typeof AdminContractorResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/observability': {
      id: '/admin_/observability'
      path: '/admin/observability'
      fullPath: '/admin/observability'
      preLoaderRoute: typeof AdminObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/traces': {
      id: '/admin_/traces'
      path: '/admin/traces'
      fullPath: '/admin/traces'
      preLoaderRoute: typeof AdminTracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/confirmation': {
      id: '/booking/confirmation'
      path: '/booking/confirmation'
      fullPath: '/booking/confirmation'
      preLoaderRoute: typeof BookingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/return': {
      id: '/booking/return'
      path: '/booking/return'
      fullPath: '/booking/return'
      preLoaderRoute: typeof BookingReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$websiteId': {
      id: '/lp/$websiteId'
      path: '/lp/$websiteId'
      fullPath: '/lp/$websiteId'
      preLoaderRoute: typeof LpWebsiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$websiteId': {
      id: '/setup/$websiteId'
      path: '/setup/$websiteId'
      fullPath: '/setup/$websiteId'
      preLoaderRoute: typeof SetupWebsiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/plumber': {
      id: '/template/plumber'
      path: '/template/plumber'
      fullPath: '/template/plumber'
      preLoaderRoute: typeof TemplatePlumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/landscape': {
      id: '/templates/landscape'
      path: '/templates/landscape'
      fullPath: '/templates/landscape'
      preLoaderRoute: typeof TemplatesLandscapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter': {
      id: '/templates/painter'
      path: '/templates/painter'
      fullPath: '/templates/painter'
      preLoaderRoute: typeof TemplatesPainterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter1': {
      id: '/templates/painter1'
      path: '/templates/painter1'
      fullPath: '/templates/painter1'
      preLoaderRoute: typeof TemplatesPainter1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter10': {
      id: '/templates/painter10'
      path: '/templates/painter10'
      fullPath: '/templates/painter10'
      preLoaderRoute: typeof TemplatesPainter10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter11': {
      id: '/templates/painter11'
      path: '/templates/painter11'
      fullPath: '/templates/painter11'
      preLoaderRoute: typeof TemplatesPainter11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter12': {
      id: '/templates/painter12'
      path: '/templates/painter12'
      fullPath: '/templates/painter12'
      preLoaderRoute: typeof TemplatesPainter12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter13': {
      id: '/templates/painter13'
      path: '/templates/painter13'
      fullPath: '/templates/painter13'
      preLoaderRoute: typeof TemplatesPainter13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter14': {
      id: '/templates/painter14'
      path: '/templates/painter14'
      fullPath: '/templates/painter14'
      preLoaderRoute: typeof TemplatesPainter14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter15': {
      id: '/templates/painter15'
      path: '/templates/painter15'
      fullPath: '/templates/painter15'
      preLoaderRoute: typeof TemplatesPainter15RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter16': {
      id: '/templates/painter16'
      path: '/templates/painter16'
      fullPath: '/templates/painter16'
      preLoaderRoute: typeof TemplatesPainter16RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter17': {
      id: '/templates/painter17'
      path: '/templates/painter17'
      fullPath: '/templates/painter17'
      preLoaderRoute: typeof TemplatesPainter17RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter18': {
      id: '/templates/painter18'
      path: '/templates/painter18'
      fullPath: '/templates/painter18'
      preLoaderRoute: typeof TemplatesPainter18RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter4': {
      id: '/templates/painter4'
      path: '/templates/painter4'
      fullPath: '/templates/painter4'
      preLoaderRoute: typeof TemplatesPainter4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter5': {
      id: '/templates/painter5'
      path: '/templates/painter5'
      fullPath: '/templates/painter5'
      preLoaderRoute: typeof TemplatesPainter5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter6': {
      id: '/templates/painter6'
      path: '/templates/painter6'
      fullPath: '/templates/painter6'
      preLoaderRoute: typeof TemplatesPainter6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter7': {
      id: '/templates/painter7'
      path: '/templates/painter7'
      fullPath: '/templates/painter7'
      preLoaderRoute: typeof TemplatesPainter7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/painter8': {
      id: '/templates/painter8'
      path: '/templates/painter8'
      fullPath: '/templates/painter8'
      preLoaderRoute: typeof TemplatesPainter8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/plumber': {
      id: '/templates/plumber'
      path: '/templates/plumber'
      fullPath: '/templates/plumber'
      preLoaderRoute: typeof TemplatesPlumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/calendar-repair': {
      id: '/api/admin/calendar-repair'
      path: '/api/admin/calendar-repair'
      fullPath: '/api/admin/calendar-repair'
      preLoaderRoute: typeof ApiAdminCalendarRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/message': {
      id: '/api/agent/message'
      path: '/api/agent/message'
      fullPath: '/api/agent/message'
      preLoaderRoute: typeof ApiAgentMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/booking': {
      id: '/api/cron/booking'
      path: '/api/cron/booking'
      fullPath: '/api/cron/booking'
      preLoaderRoute: typeof ApiCronBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/generation-monitor': {
      id: '/api/cron/generation-monitor'
      path: '/api/cron/generation-monitor'
      fullPath: '/api/cron/generation-monitor'
      preLoaderRoute: typeof ApiCronGenerationMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/lead-retention': {
      id: '/api/cron/lead-retention'
      path: '/api/cron/lead-retention'
      fullPath: '/api/cron/lead-retention'
      preLoaderRoute: typeof ApiCronLeadRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/pipedream-inbox': {
      id: '/api/cron/pipedream-inbox'
      path: '/api/cron/pipedream-inbox'
      fullPath: '/api/cron/pipedream-inbox'
      preLoaderRoute: typeof ApiCronPipedreamInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/stripe-inbox': {
      id: '/api/cron/stripe-inbox'
      path: '/api/cron/stripe-inbox'
      fullPath: '/api/cron/stripe-inbox'
      preLoaderRoute: typeof ApiCronStripeInboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pipedream/webhook': {
      id: '/api/pipedream/webhook'
      path: '/api/pipedream/webhook'
      fullPath: '/api/pipedream/webhook'
      preLoaderRoute: typeof ApiPipedreamWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-logs': {
      id: '/api/public/agent-logs'
      path: '/api/public/agent-logs'
      fullPath: '/api/public/agent-logs'
      preLoaderRoute: typeof ApiPublicAgentLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resend/webhook': {
      id: '/api/resend/webhook'
      path: '/api/resend/webhook'
      fullPath: '/api/resend/webhook'
      preLoaderRoute: typeof ApiResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/connect-webhook': {
      id: '/api/stripe/connect-webhook'
      path: '/api/stripe/connect-webhook'
      fullPath: '/api/stripe/connect-webhook'
      preLoaderRoute: typeof ApiStripeConnectWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/$websiteId/': {
      id: '/setup/$websiteId/'
      path: '/'
      fullPath: '/setup/$websiteId/'
      preLoaderRoute: typeof SetupWebsiteIdIndexRouteImport
      parentRoute: typeof SetupWebsiteIdRoute
    }
    '/setup/$websiteId/availability': {
      id: '/setup/$websiteId/availability'
      path: '/availability'
      fullPath: '/setup/$websiteId/availability'
      preLoaderRoute: typeof SetupWebsiteIdAvailabilityRouteImport
      parentRoute: typeof SetupWebsiteIdRoute
    }
    '/setup/$websiteId/calendar': {
      id: '/setup/$websiteId/calendar'
      path: '/calendar'
      fullPath: '/setup/$websiteId/calendar'
      preLoaderRoute: typeof SetupWebsiteIdCalendarRouteImport
      parentRoute: typeof SetupWebsiteIdRoute
    }
    '/setup/$websiteId/payments': {
      id: '/setup/$websiteId/payments'
      path: '/payments'
      fullPath: '/setup/$websiteId/payments'
      preLoaderRoute: typeof SetupWebsiteIdPaymentsRouteImport
      parentRoute: typeof SetupWebsiteIdRoute
    }
    '/user/$userId/edit-mode': {
      id: '/user/$userId/edit-mode'
      path: '/edit-mode'
      fullPath: '/user/$userId/edit-mode'
      preLoaderRoute: typeof UserUserIdEditModeRouteImport
      parentRoute: typeof UserUserIdRoute
    }
    '/api/booking/attachments/proof': {
      id: '/api/booking/attachments/proof'
      path: '/api/booking/attachments/proof'
      fullPath: '/api/booking/attachments/proof'
      preLoaderRoute: typeof ApiBookingAttachmentsProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking/attachments/$attachmentId/download': {
      id: '/api/booking/attachments/$attachmentId/download'
      path: '/api/booking/attachments/$attachmentId/download'
      fullPath: '/api/booking/attachments/$attachmentId/download'
      preLoaderRoute: typeof ApiBookingAttachmentsAttachmentIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SetupWebsiteIdRouteChildren {
  SetupWebsiteIdAvailabilityRoute: typeof SetupWebsiteIdAvailabilityRoute
  SetupWebsiteIdCalendarRoute: typeof SetupWebsiteIdCalendarRoute
  SetupWebsiteIdPaymentsRoute: typeof SetupWebsiteIdPaymentsRoute
  SetupWebsiteIdIndexRoute: typeof SetupWebsiteIdIndexRoute
}

const SetupWebsiteIdRouteChildren: SetupWebsiteIdRouteChildren = {
  SetupWebsiteIdAvailabilityRoute: SetupWebsiteIdAvailabilityRoute,
  SetupWebsiteIdCalendarRoute: SetupWebsiteIdCalendarRoute,
  SetupWebsiteIdPaymentsRoute: SetupWebsiteIdPaymentsRoute,
  SetupWebsiteIdIndexRoute: SetupWebsiteIdIndexRoute,
}

const SetupWebsiteIdRouteWithChildren = SetupWebsiteIdRoute._addFileChildren(
  SetupWebsiteIdRouteChildren,
)

interface UserUserIdRouteChildren {
  UserUserIdEditModeRoute: typeof UserUserIdEditModeRoute
}

const UserUserIdRouteChildren: UserUserIdRouteChildren = {
  UserUserIdEditModeRoute: UserUserIdEditModeRoute,
}

const UserUserIdRouteWithChildren = UserUserIdRoute._addFileChildren(
  UserUserIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingsRoute: BookingsRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  Painter1Route: Painter1Route,
  Painter2Route: Painter2Route,
  Painter3Route: Painter3Route,
  Painter4Route: Painter4Route,
  VerifyOtpRoute: VerifyOtpRoute,
  AdminContractorResearchRoute: AdminContractorResearchRoute,
  AdminObservabilityRoute: AdminObservabilityRoute,
  AdminTracesRoute: AdminTracesRoute,
  BookingConfirmationRoute: BookingConfirmationRoute,
  BookingReturnRoute: BookingReturnRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  LpWebsiteIdRoute: LpWebsiteIdRoute,
  SetupWebsiteIdRoute: SetupWebsiteIdRouteWithChildren,
  TemplatePlumberRoute: TemplatePlumberRoute,
  TemplatesLandscapeRoute: TemplatesLandscapeRoute,
  TemplatesPainterRoute: TemplatesPainterRoute,
  TemplatesPainter1Route: TemplatesPainter1Route,
  TemplatesPainter10Route: TemplatesPainter10Route,
  TemplatesPainter11Route: TemplatesPainter11Route,
  TemplatesPainter12Route: TemplatesPainter12Route,
  TemplatesPainter13Route: TemplatesPainter13Route,
  TemplatesPainter14Route: TemplatesPainter14Route,
  TemplatesPainter15Route: TemplatesPainter15Route,
  TemplatesPainter16Route: TemplatesPainter16Route,
  TemplatesPainter17Route: TemplatesPainter17Route,
  TemplatesPainter18Route: TemplatesPainter18Route,
  TemplatesPainter4Route: TemplatesPainter4Route,
  TemplatesPainter5Route: TemplatesPainter5Route,
  TemplatesPainter6Route: TemplatesPainter6Route,
  TemplatesPainter7Route: TemplatesPainter7Route,
  TemplatesPainter8Route: TemplatesPainter8Route,
  TemplatesPlumberRoute: TemplatesPlumberRoute,
  UserUserIdRoute: UserUserIdRouteWithChildren,
  TemplatesIndexRoute: TemplatesIndexRoute,
  ApiAdminCalendarRepairRoute: ApiAdminCalendarRepairRoute,
  ApiAgentMessageRoute: ApiAgentMessageRoute,
  ApiCronBookingRoute: ApiCronBookingRoute,
  ApiCronGenerationMonitorRoute: ApiCronGenerationMonitorRoute,
  ApiCronLeadRetentionRoute: ApiCronLeadRetentionRoute,
  ApiCronPipedreamInboxRoute: ApiCronPipedreamInboxRoute,
  ApiCronStripeInboxRoute: ApiCronStripeInboxRoute,
  ApiPipedreamWebhookRoute: ApiPipedreamWebhookRoute,
  ApiPublicAgentLogsRoute: ApiPublicAgentLogsRoute,
  ApiResendWebhookRoute: ApiResendWebhookRoute,
  ApiStripeConnectWebhookRoute: ApiStripeConnectWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiBookingAttachmentsProofRoute: ApiBookingAttachmentsProofRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  ApiBookingAttachmentsAttachmentIdDownloadRoute:
    ApiBookingAttachmentsAttachmentIdDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
